version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  hikmet-test:
    build: ../hikmet
    ports:
      - 8066:8066
    restart: "on-failure"
    environment:
       VIRTUAL_HOST: hikmet.drongocompany.com
       VIRTUAL_PORT: 8066
       TIMEOUT: 100
       HTTP_PORT: 8066
       STATS_PORT: 8067
    volumes:
      - ../hikmet:/code
    ports:
      - "8066:8066"
    container_name: hikmet-test


  malik-test:
    build: ../malik
    ports:
      - 8035:8035
    restart: "on-failure"
    environment:
       VIRTUAL_HOST: malik.drongocompany.com
       VIRTUAL_PORT: 8035
       TIMEOUT: 100
       HTTP_PORT: 8035
       STATS_PORT: 8036
    volumes:
      - ../malik:/code
    ports:
      - "8035:8035"
    container_name: malik-test

  drongo-website:
    build: ../drongo-website
    ports:
      - 8020:8020
    restart: "on-failure"
    environment:
       VIRTUAL_HOST: demo.drongocompany.com
       VIRTUAL_PORT: 8020
       TIMEOUT: 100
       HTTP_PORT: 8020
       STATS_PORT: 8021
    volumes:
      - ../drongo-website:/code
    ports:
      - "8020:8020"
    container_name: drongo-website

  website:
    build: ../drongo
    ports:
      - 8050:8050
    restart: "on-failure"
    environment:
       VIRTUAL_HOST: drongocompany.com
       VIRTUAL_PORT: 8050
       TIMEOUT: 100
       HTTP_PORT: 8050
       STATS_PORT: 8051
    volumes:
      - ../drongo:/code
    ports:
      - "8050:8050"
    container_name: drongo-demo

networks:
  default:
    external:
      name: nginx-proxy